### PR TITLE
case-insensitive

### PR DESCRIPTION
**Pull request by landfillbaby**

### CODE REVIEW

**Comment by Megabyteceer** [comment]
Is it change for //todo: work as well as //TODO: ?

**Comment by landfillbaby** [comment]
yes

**Comment by Megabyteceer** [comment]
case-insensitive comparation is less effective. I'm not sure this feature is really necessary. You can't just replace all todo comments to upper case.

**Comment by landfillbaby** [comment]
maybe i'll make it an option in the configuration file, so it can be on or off. i'll work on it tomorrow

**Comment by landfillbaby** [comment]
should i increment the config version number when i do it too?

**Comment by Megabyteceer** [comment]
IMO you and anyone else do not need this feature. Do not waste your time.
Lets keep this PR for discuss for a while. And check if some body will find it useful.

**Comment by basil83** [comment]
It doesn't support UTF-8 . As a Korean, I can't use NPPTaskList.

(And I don't know where to report bugs.)

**Pull request closed without merging**
